#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely with a sleep of 2 seconds
# eternity unless it is killed, not so ethernal after all :)

while true;
do
	echo "To infinity and beyond";
	sleep 2
done
