#!/usr/bin/env bash
# Displays 1 to 100 where "FizzBuzz" is displayed if the number is a multiple
# of 3 and 5, "Fizz" if the number is a multiple of 3, and "Buzz" if the
# number is a multiple of 5. Otherwise it displays the number

n=1

while [ $n -le 100 ]; do
      if [ $((n%5)) -eq 0 ] && [ $((n%3)) -eq 0 ]; then
	  echo "FizzBuzz"
      elif [ $((n%5)) -eq 0 ]; then
	  echo "Buzz"
      elif [ $((n%3)) -eq 0 ]; then
	  echo "Fizz"
      else
	  echo "$n"
      fi
      n=$((n+1))
done
