#!/usr/bin/env bash
# Display "Best School" 10 times and displays "Hi" for the 9th iteration

n=0

while [ $n -lt 10 ]; do
      echo "Best School"
      if [ $n -eq 8 ]; then
	  echo "Hi"
      fi
      n=$((n+1))
done
