#!/usr/bin/env bash
# Loops from 1 to 10 and displays "bad luck" for the 4th iteration,
# "good luck" for the 8th iteration, and "Best School" for others

n=1

while [ $n -le 10 ]; do
      if [ $n -eq 4 ]; then
      	 echo "bad luck"
      elif [ $n -eq 8 ]; then
	 echo "good luck"
      else
	 echo "Best School"
      fi
      n=$((n+1))
done
