#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59

hour=0

while [ $hour -lt 13 ]; do
      echo "Hour: $hour"
      n=1
      while [ $n -le 59 ]; do
      	  echo "$i"
	  n=$((n+1))
      done
      hour=$((hour+1))
done
